#!/usr/bin/env node
import arg from 'arg';
import {exit} from 'node:process';
import {writeFile} from 'node:fs/promises';
import {$} from 'zx';

import preflight from './lib/preflight.js';

const args = arg(
  {
    '--help': Boolean,
    '--version': Boolean,
    '-h': '--help',
    '-v': '--version',

    '--calendar': String,
    '--exec': String,
    '--name': String,
    '--timespan': String,

    '-c': '--calendar',
    '-n': '--name',
    '-x': '--exec',
    '-t': '--timespan',
  },
  {permissive: true}
);

const {name, execStart, timer, timerType} = await preflight(args);

const serviceContent = `#${name}.service
[Unit]
Description=Autogenerated service unit for "${name}"

[Service]
Type=oneshot
ExecStart=${execStart}

[Install]
WantedBy=default.target
`;

const timerContent = `#${name}.timer
[Unit]
Description=Autogenerated timer unit for "${name}"

[Timer]
${(timerType == 'timespan' && `OnUnitActiveSec=${timer}`) || `OnCalendar=${timer}`}\
Unit=${name}.service

[Install]
WantedBy=timers.target
`;

try {
  let fileName = `${process.env.HOME}/.config/systemd/user/${name}.service`;
  await writeFile(fileName, serviceContent, {mode: 0o660});
  console.info(`${fileName} created successfully.`);
  fileName = `${process.env.HOME}/.config/systemd/user/${name}.timer`;
  await writeFile(fileName, timerContent, {mode: 0o660});
  console.info(`${fileName} created successfully.`);
  await $`systemctl --user enable ${name}.timer &&\
          systemctl --user start ${name}.timer`;
} catch (error) {
  console.error(error.message ? error.message : error.stderr);
  exit(1);
}
