#!/usr/bin/env node
/* eslint-disable security/detect-non-literal-fs-filename */
import arg from 'arg';
import {writeFile} from 'node:fs/promises';
import {exit} from 'node:process';
import {$} from 'zx';

import preflight from './lib/preflight.js';

const arguments_ = arg(
  {
    '--calendar': String,
    '--exec': String,
    '--help': Boolean,
    '--name': String,

    '--timespan': String,
    '--version': Boolean,
    '-c': '--calendar',
    '-h': '--help',

    '-n': '--name',
    '-t': '--timespan',
    '-v': '--version',
    '-x': '--exec',
  },
  {permissive: true}
);

const {execStart, name, timer, timerType} = await preflight(arguments_);

const serviceContent = `#${name}.service
[Unit]
Description=Autogenerated service unit for "${name}"

[Service]
Type=oneshot
ExecStart=${execStart}

[Install]
WantedBy=default.target
`;

const timerContent = `#${name}.timer
[Unit]
Description=Autogenerated timer unit for "${name}"

[Timer]
${(timerType === 'timespan' && `OnUnitActiveSec=${timer}`) || `OnCalendar=${timer}`}\
Unit=${name}.service

[Install]
WantedBy=timers.target
`;

try {
  let fileName = `${process.env.HOME}/.config/systemd/user/${name}.service`;
  await writeFile(fileName, serviceContent, {mode: 0o660});
  console.info(`${fileName} created successfully.`);
  fileName = `${process.env.HOME}/.config/systemd/user/${name}.timer`;
  await writeFile(fileName, timerContent, {mode: 0o660});
  console.info(`${fileName} created successfully.`);
  await $`systemctl --user enable ${name}.timer &&\
          systemctl --user start ${name}.timer`;
} catch (error) {
  console.error(error.message || error.stderr);
  exit(1);
}
