export function serviceTemplate({execStart, name}) {
  return `#${name}.service
[Unit]
Description=Autogenerated service unit for "${name}"

[Service]
Type=oneshot
ExecStart=${execStart}
`;
}

export function timerTemplate({calendar, name, timeSpan}) {
  return `#${name}.timer
[Unit]
Description=Autogenerated timer unit for "${name}"

[Timer]
${(timeSpan && `OnUnitActiveSec=${timeSpan}`) || `OnCalendar=${calendar}`}
Unit=${name}.service

[Install]
WantedBy=timers.target
`;
}
