export const serviceTemplate = ({execStart, name}) => `#${name}.service
[Unit]
Description=Autogenerated service for "${name}"

[Service]
Type=oneshot
ExecStart=${execStart}
`;

export const timerTemplate = ({name, on, timerType}) => `#${name}.timer
[Unit]
Description=Autogenerated timer for "${name}"

[Timer]
${(timerType === 'timeSpan' && `OnUnitActiveSec=${on}`) || `OnCalendar=${on}`}
${timerType === 'timeSpan' && 'OnBootSec=5s'}
Unit=${name}.service

[Install]
WantedBy=timers.target
`;
