/* eslint-disable @typescript-eslint/no-unnecessary-condition */
export const serviceTemplate = ({
  execStart,
  name,
}: {
  [key: string]: string;
}) => `#${name}.service
[Unit]
Description=Autogenerated service for "${name}"

[Service]
Type=oneshot
ExecStart=${execStart}
`;

export const timerTemplate = ({
  name,
  on,
  timerType,
}: {
  [key: string]: string;
}) => `#${name}.timer
[Unit]
Description=Autogenerated timer for "${name}"

[Timer]
${(timerType === 'timeSpan' && `OnUnitActiveSec=${on}`) || `OnCalendar=${on}`}
${(timerType === 'timeSpan' && 'OnBootSec=5s\n') || ''}Unit=${name}.service

[Install]
WantedBy=timers.target
`;
