export const serviceTemplate = ({execStart, name}) => `#${name}.service
[Unit]
Description=Autogenerated service unit for "${name}"

[Service]
Type=oneshot
ExecStart=${execStart}
`;

export const timerTemplate = ({name, on, timerType}) => `#${name}.timer
[Unit]
Description=Autogenerated timer unit for "${name}"

[Timer]
${(timerType === 'timeSpan' && `OnActiveSec=${on}`) || `OnCalendar=${on}`}
Unit=${name}.service

[Install]
WantedBy=timers.target
`;
